package schemas.dynamics.microsoft.page.salesorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-20T12:52:20.104+01:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "salesorder_Service", 
                  wsdlLocation = "file:/home/ramza/Downloads/ws-nav-api/ws-nav-api/src/main/resources/wsdl/salesorder.wsdl",
                  targetNamespace = "urn:microsoft-dynamics-schemas/page/salesorder") 
public class SalesorderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:microsoft-dynamics-schemas/page/salesorder", "salesorder_Service");
    public final static QName SalesorderPort = new QName("urn:microsoft-dynamics-schemas/page/salesorder", "salesorder_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ramza/Downloads/ws-nav-api/ws-nav-api/src/main/resources/wsdl/salesorder.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SalesorderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ramza/Downloads/ws-nav-api/ws-nav-api/src/main/resources/wsdl/salesorder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SalesorderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SalesorderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesorderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SalesorderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SalesorderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SalesorderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SalesorderPort
     */
    @WebEndpoint(name = "salesorder_Port")
    public SalesorderPort getSalesorderPort() {
        return super.getPort(SalesorderPort, SalesorderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesorderPort
     */
    @WebEndpoint(name = "salesorder_Port")
    public SalesorderPort getSalesorderPort(WebServiceFeature... features) {
        return super.getPort(SalesorderPort, SalesorderPort.class, features);
    }

}
