package schemas.dynamics.microsoft.page.transferorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-20T14:31:10.598+01:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "transferorder_Service", 
                  wsdlLocation = "file:/home/ramza/Downloads/ws-nav-api/ws-nav-api/src/main/resources/wsdl/transferorder.wsdl",
                  targetNamespace = "urn:microsoft-dynamics-schemas/page/transferorder") 
public class TransferorderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:microsoft-dynamics-schemas/page/transferorder", "transferorder_Service");
    public final static QName TransferorderPort = new QName("urn:microsoft-dynamics-schemas/page/transferorder", "transferorder_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ramza/Downloads/ws-nav-api/ws-nav-api/src/main/resources/wsdl/transferorder.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransferorderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ramza/Downloads/ws-nav-api/ws-nav-api/src/main/resources/wsdl/transferorder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransferorderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransferorderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransferorderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TransferorderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TransferorderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TransferorderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TransferorderPort
     */
    @WebEndpoint(name = "transferorder_Port")
    public TransferorderPort getTransferorderPort() {
        return super.getPort(TransferorderPort, TransferorderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransferorderPort
     */
    @WebEndpoint(name = "transferorder_Port")
    public TransferorderPort getTransferorderPort(WebServiceFeature... features) {
        return super.getPort(TransferorderPort, TransferorderPort.class, features);
    }

}
