
package com.javacodegeeks.ws.product_service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-10-10T12:23:59.475+01:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "error", targetNamespace = "http://ws.javacodegeeks.com/product-service/types")
public class ErrorMessage extends Exception {
    
    private com.javacodegeeks.ws.product_service.types.Error error;

    public ErrorMessage() {
        super();
    }
    
    public ErrorMessage(String message) {
        super(message);
    }
    
    public ErrorMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorMessage(String message, com.javacodegeeks.ws.product_service.types.Error error) {
        super(message);
        this.error = error;
    }

    public ErrorMessage(String message, com.javacodegeeks.ws.product_service.types.Error error, Throwable cause) {
        super(message, cause);
        this.error = error;
    }

    public com.javacodegeeks.ws.product_service.types.Error getFaultInfo() {
        return this.error;
    }
}
