package com.javacodegeeks.ws.product_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-10-10T12:23:59.480+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://ws.javacodegeeks.com/product-service", name = "Product")
@XmlSeeAlso({com.javacodegeeks.ws.product_service.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Product {

    @WebResult(name = "productResponse", targetNamespace = "http://ws.javacodegeeks.com/product-service/types", partName = "response")
    @WebMethod
    public com.javacodegeeks.ws.product_service.types.ProductResponse getProductDetails(
        @WebParam(partName = "request", name = "productRequest", targetNamespace = "http://ws.javacodegeeks.com/product-service/types")
        com.javacodegeeks.ws.product_service.types.ProductRequest request
    ) throws ErrorMessage;
}
